version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    links:
      - db
    ports:
      - 1998:1998
    networks:
      - cupizz
    depends_on:
      - redis
      - db
  db:
    image: postgres
    ports:
      - 19981:5432
    environment:
      POSTGRES_PASSWORD: cupizz2020
      POSTGRES_USER: postgres
      POSTGRES_DB: cupizz
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    networks:
      - cupizz
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    networks:
      - cupizz
    depends_on:
      - db
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    networks:
      - cupizz

networks:
  cupizz:
