version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile

    # Overrides default command so things don't shut down after the process ends.
    volumes:
      - .:/cubizz
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/data?schema=public
      - JWT_SECRET_KEY=hieren
      - NODE_ENV=development
    links:
      - db
    ports:
      - 1998:1998
    networks:
      - cubizz
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 19981:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
    networks:
      - cubizz

networks:
  cubizz:
