version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - db
    networks:
      - cupizz
    ports:
      - '1998:1998'
      - '5555:5555'
    depends_on:
        - redis
        - db
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cupizz
    depends_on:
      - web
      - db
      - redis
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
    volumes:
        - database:/var/lib/postgresql/data
    networks:
      - cupizz
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/redis-data:/data
    restart: unless-stopped
    networks:
      - cupizz

networks:
  cupizz:

volumes:
  database:
    