version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - db
    networks:
      - cupizz
    ports:
      - '1998:1998'
      - '5555:5555'
    depends_on:
        - redis
        - db
  nginx:
    image: nginx:stable-alpine
    volumes:
      - web-root:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cupizz
    depends_on:
      - web
      - db
      - redis
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email hienlh1298@gmail.com --agree-tos --no-eff-email --force-renewal -d cupizz.cf  -d www.cupizz.cf
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
    volumes:
        - database:/var/lib/postgresql/data
    networks:
      - cupizz
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/redis-data:/data
    restart: unless-stopped
    networks:
      - cupizz

networks:
  cupizz:

volumes:
  database:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/cupizz/web-root/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/cupizz/dhparam/
      o: bind
    