version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile

    volumes:
      - .:/cupizz:cached
    command: sleep infinity
    env_file:
      - .env
    links:
      - db
    ports:
      - 1998:1998
    networks:
      - cupizz
    depends_on:
        - redis
        - db
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 19981:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
    networks:
      - cupizz
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/redis-data:/data
    restart: unless-stopped
    networks:
      - cupizz

networks:
  cupizz:
