version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile

    volumes:
      - .:/cubizz:cached
    command: sleep infinity
    env_file:
      - .env
    links:
      - db
    ports:
      - 1998:1998
    networks:
      - cubizz
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 19981:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
    networks:
      - cubizz

networks:
  cubizz:
