version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/data?schema=public
      - JWT_SECRET_KEY=hieren
    links:
      - db
    networks:
      - cubizz
    ports:
      - '1998:1998'
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cubizz
    depends_on:
      - web
      - db
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 19981:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
    volumes:
        - database:/var/lib/postgresql/data
    networks:
      - cubizz

networks:
  cubizz:

volumes:
  database:
    