export const universities = [
    "Đại học Quốc gia Thành phố Hồ Chí Minh (Vietnam National University, Ho Chi Minh City)",
    "Trường Đại học Bách khoa (Ho Chi Minh University of Technology)",
    "Trường Đại học Quốc tế (VNUHCM - International University)",
    "Trường Đại Học Kinh Tế và Luật (VNUHCM - University of Economics and Law)",
    "Trường Đại học Khoa học Tự nhiên (VNUHCM - University of Science)",
    "Trường Đại học Khoa học Xã hội và Nhân văn (VNUHCM - University of Social Sciences and Humanities)",
    "Trường Đại học Công Nghệ Thông Tin (VNUHCM - University of Information Technology)",
    "Trường Đại học An Giang (VNUHCM - University of An Giang)",
    "Khoa Y (Faculty of Medicine)",
    "Trung tâm nghiên cứu tài nguyên và môi trường (Institute for Resources and Environment)",
    "Đại học Quốc gia Hà Nội (Vietnam National University, Hanoi)",
    "Trường Đại học Kinh tế (University of Economics and Business)",
    "Trường Đại Học Giáo Dục (University of Education)",
    "Trường Đại học Ngoại ngữ (University of Languages and International Studies)",
    "Trường Đại học Khoa học Tự nhiên (Hanoi University of Science)",
    "Trường Đại học Khoa học Xã hội và Nhân văn (University of Social Science and Humanity)",
    "Trường Đại học Công nghệ (University of Engineering and Technology)",
    "Khoa Luật (School of Law)",
    "Khoa Y Dược (School of Medicine and Pharmacy)",
    "Khoa Quốc tế (School of International Studies)",
    "formerly Hanoi University of Technology - Trường Đại học Bách Khoa Hà Nội (Hanoi University of Science and Technology)",
    "Đại học Sư phạm Kỹ thuật Thành phố Hồ Chí Minh (Ho Chi Minh City University of Technology and Education)",
    "Đại học Cần Thơ; formerly Viện Đại học Cần Thơ [1966-1975] (Can Tho University)",
    "Trường Đại học Ngoại Thương Hà Nội (Hanoi Foreign Trade University)",
    "Trường Đại học Y Hà Nội (Hanoi Medical University)",
    "Trường Đại học Sư Phạm Hà Nội (Hanoi National University of Education)",
    "Trường Đại học Hà Nội, formerly Hanoi University of Foreign Studies - Trường Đại học Ngoại Ngữ Hà Nội (Hanoi University)",
    "Đại học Nông nghiệp Hà Nội, formerly Đại học Nông nghiệp 1 Hà Nội (Hanoi University of Agriculture)",
    "Trường Đại học Xây Dựng (Hanoi University of Civil Engineering)",
    "Đại học Công Nghiệp Hà Nội, high-technology and engineering (Hanoi University of Industry)",
    "Đại học Tài nguyên và Môi trường Hà Nội (Hanoi University of Natural Resources and Environment)",
    "Trường Đại học Mỏ - Địa chất (Hanoi University of Mining and Geology)",
    "Đại học Y Dược Thành phố Hồ Chí Minh (Ho Chi Minh City Medicine and Pharmacy University)",
    "Đại học Mở Thành phố Hồ Chí Minh (Ho Chi Minh City Open University)",
    "Trường Đại học Kinh tế Quốc dân (National Economics University)",
    "Đại học Nông lâm Thành phố Hồ Chí Minh (Nông Lâm University (Agriculture and Forestry))",
    "Trường Đại học Kinh tế Thành phố Hồ Chí Minh (University of Economics, Ho Chi Minh City)",
    "Trường Đại học Ngân hàng Thành phố Hồ Chí Minh (Banking University Ho Chi Minh City)",
    "Trường Đại học Giao thông Vận tải (University of Transport and Communications)",
    "became a member of VNU-HCM from 2017 (An Giang University (Đại học An Giang))",
    "Đại học Đà Lạt; formerly, Viện Đại học Đà Lạt (Dalat University)",
    "Đại học Đồng Nai (Dong Nai University)",
    "Trường Đại học Điện lực (Electric Power University)",
    "Đại học Y dược Hải Phòng (Hai Phong Medical University)",
    "Đại học Hải Phòng (Hai Phong University)",
    "Đại học Kiến trúc Hà Nội (Hanoi Architectural University)",
    "Đại học Kiến trúc Thành phố Hồ Chí Minh (Ho Chi Minh City University of Architecture)",
    "Đại học Mỹ thuật Thành phố Hồ Chí Minh (Ho Chi Minh City University of Fine Arts)",
    "Đại học Công nghiệp Thành phố Hồ Chí Minh (Ho Chi Minh City University of Industry)",
    "Đại học Vinh (Vinh University)",
    "Đại học Huế; formerly Viện Đại học Huế [1957-1975] (Hue University)",
    "Trường Đại học Nông lâm Huế (Hue College of Agriculture and Forestry)",
    "Trường Đại học Nghệ thuật Huế (Hue College of Arts)",
    "Trường Đại học Kinh tế Huế (Hue College of Economics)",
    "Hue College of Foreign Languages",
    "Trường Đại học Y Dược, Đại học Huế (Hue University of Medicine and Pharmacy)",
    "Trường Đại học Sư phạm Huế (Hue College of Teacher Training)",
    "Trường Đại học Ngoại Thương Thành phố Hồ Chí Minh (Ho Chi Minh Foreign Trade University)",
    "Đại học Mở Hà Nội (Hanoi Open University)",
    "Trường Đại học Luật Hà Nội (Hanoi University of Law)",
    "Trường Đại học Sư Phạm Hà Nội 2 (Hanoi Pedagogical University N°2)",
    "Đại học Thái Nguyên (Thai Nguyen University), Thai Nguyen",
    "Trường Đại học Kĩ thuật Công nghiệp Thái Nguyên (Thai Nguyen University of Technology)",
    "Trường Đại học Sư phạm Thái Nguyên (Thai Nguyen University of Education)",
    "Đại học Đà Nẵng (University of Da Nang)",
    "Trường Đại học Sư phạm Đà Nẵng (Da Nang College of Education)",
    "Trường Đại học Ngoại ngữ Đà Nẵng (Da Nang College of Foreign Languages)",
    "Trường Đại học Công nghệ Thông tin Đà Nẵng (Da Nang College of Information Technology)",
    "Trường Cao đẳng công nghệ Đà Nẵng (Da Nang College of Technology)",
    "Chi nhánh Trường Đại học Đà Nẵng tại Kontum (Da Nang University Branch at Kontum)",
    "Trường Đại học Kinh tế Đà Nẵng (Da Nang University of Economics)",
    "Trường Đại học Bách khoa Đà Nẵng (Da Nang University of Technology)",
    "Trường Đại học Lao động - Xã hội (University of Labour - Social Affairs)",
    "Đại học Lao Động - Xã Hội cơ sở phía Nam (University of Labour and Social Affairs 2, Ho Chi Minh City)",
    "Đại học Nông - Lâm Bắc Giang (Bac Giang University of Agriculture and Forestry)",
    "Đại Học Kỹ Thuật- Công Nghệ Cần Thơ (Cần Thơ University of Technology)",
    "Đại học Đồng Tháp (Dong Thap University of Education)",
    "Đại học Hồng Đức (Hong Duc University)",
    "Đại học Hùng Vương - Phú Thọ (Hung Vuong University)",
    "Đại học Thuỷ sản Nha Trang (Nha Trang Fisheries University)",
    "Đại học Nha Trang (Nha Trang University)",
    "Đại học Y Khoa Phạm Ngọc Thạch (Pham Ngoc Thach University of Medicine)",
    "Đại học Quy Nhơn (Quy Nhon University)",
    "Đại học Tây Bắc (Tay Bac University)",
    "Đại học Tây Nguyên (Tay Nguyen University)",
    "Đại học Y dược Thái Bình (Thai Binh University of Medicine)",
    "Đại học Tôn Đức Thắng, Thành phố Hồ Chí Minh (Ton Duc Thang University)",
    "Đại học Trà Vinh, Thành phố Trà Vinh (Tra Vinh University)",
    "Đại học Giao thông Vận tải (University of Communications and Transportation)",
    "Đại học Tai chinh Ke Toan (University of Finance and Accountancy)",
    "Đại học Thủy sản (University of Fisheries)",
    "Đại học Lâm nghiệp (Vietnam Forestry University)",
    "Đại học Hàng hải (Vietnam Maritime University)",
    "Đại học Thương mại (Vietnam University of Commerce)",
    "Đại học Việt-Đức (Vietnamese-German University)",
    "Đại học Thủy lợi (Water Resources University) ",
    "Đại học văn hóa Hà Nội (Ha Noi university of culture)",
    "Trường Đại học Công nghệ Giao thông Vận tải (University Of Transport Technology)",
    "Trường Đại học Y tế Công cộng (Hanoi School of Public Health)",
    "Trường Đại học Dược Hà Nội (Hanoi University of Pharmacy)",
    "Trường Đại học Sư phạm Thành phố Hồ Chí Minh (Ho Chi Minh City University of Pedagogy)",
    "Trường Đại học Giao Thông Vận Tải Thành phố Hồ Chí Minh (Ho Chi Minh City University of Transportation)",
    "Trường Đại học Công Đoàn (Trade Union University)",
    "Học viện Tài chính Kế toán (Academy of Finance and Accounting)",
    "Học viện Tài chính Việt Nam (Academy of Finance of Vietnam)",
    "Học viện Ngân hàng Việt Nam (Banking Academy of Vietnam)",
    "Học viện Ngoại giao Việt Nam (Diplomatic Academy of Vietnam)",
    "Học viện Chính trị - Hành chính Quốc gia Hồ Chí Minh (Ho Chi Minh National Academy of Politics and Public Administration)",
    "Học viện Báo chí và Tuyên truyền Việt Nam (Academy of Journalism and Communication)",
    "Học viện Hành chính Việt Nam (National Academy of Public Administration)",
    "Institut de la Francophonie pour l'Informatique",
    "Học viện Quan hệ Quốc tế (Institute for International Relations)",
    "Học viện Quản lý Giáo dục Việt Nam (National Institute of Education Management)",
    "Học viện Công nghệ Bưu chính Viễn thông (Posts and Telecommunications Institute of Technology)",
    "Viện Hàn lâm Khoa học và Công nghệ Việt Nam (Vietnam Academy of Science and Technology)",
    "Viện Khoa học Xã hội Việt Nam (Vietnam Academy of Social Sciences)",
    "Học viện Khoa học Xã hội Việt Nam (Graduate Academy of Social Sciences)",
    "Học viện Hàng không Việt Nam (Vietnam Aviation Academy)",
    "Vietnam University of Traditional Medicine",
    "Học viện Sân Khấu Điện Ảnh Hà Nội (Hanoi Academy of Theatre and Cinema)",
    "Nhạc viện Hà Nội (Hanoi Conservatory of Music)",
    "Nhạc viện thành phố Hồ Chí Minh (Ho Chi Minh City Conservatory)",
    "Nhạc viện Huế (Hue Conservatory)",
    "Học viện Kỹ thuật Mật mã Việt Nam (Academy of Cryptography Techniques of Vietnam)",
    "Học viện Biên phòng Việt Nam (Border Defense Force Academy)",
    "Học viện Kỹ thuật Quân sự Việt Nam (Le Quy Don Technical University), also known as Le Quy Don University of Science and Technology",
    "Học viện Quốc phòng Việt Nam (National Defense Academy of Vietnam)",
    "Học viện Hậu cần Việt Nam (Vietnam Academy of Logistics)",
    "Học viện Khoa học Quân sự Việt Nam (Vietnam Academy of Military Science)",
    "Học viện Phòng không - Không quân Việt Nam (Vietnam Air and Air Defense Forces Academy)",
    "Học viện Lục quân Đà Lạt (Vietnam Military Academy, Dalat)",
    "Học viện Quân y Việt Nam (Vietnam Military Medical Academy)",
    "Học viện Chính trị Quân sự Việt Nam (Vietnam Military Political Academy)",
    "Học viện Hải quân Việt Nam (Vietnam Naval Academy)",
    "Đại học Quốc tế Bắc Hà (Bac Ha International University)",
    "Đại học Bình Dương - BDU (Binh Duong University)",
    "Đại học Đông Á (Đông Á University)",
    "Đại học Duy Tân - DTU (Duy Tan University)",
    "Đại học FPT (FPT University)",
    "Đại học Fulbright Việt Nam (Fulbright University Vietnam)",
    "Đại học Gia Định (Gia Đinh University)",
    "Hai Phong Private University",
    "Đại học Kinh Doanh và Công Nghệ Hà Nội - HUBT (Hanoi University of Business and Technology)",
    "Đại học Hùng Vương TPHCM - DHV (HCMC Hung Vuong University)",
    "Đại học Dân lập Ngoại ngữ Tin học Thành phố Hồ Chí Minh (Ho Chi Minh City University of Foreign Languages and Information Technology)",
    "Đại học Dân lập Kỹ thuật Công nghệ Thành phố Hồ Chí Minh; HUTECH (Ho Chi Minh City University of Technology - HUTECH)",
    "Đại học Hoa Sen - HSU (Hoa Sen University)",
    "Đại học Hồng Bàng - HBU (Hong Bang University)",
    "Đại học Kinh Tế Công Nghiệp Long An - DLA or LAU (Long An University of Economics and Industry)",
    "Đại học Nguyễn Tất Thành - NTU (Nguyen Tat Thanh University)",
    "Trường Đại học Dân lập Phú Xuân, Huế (Phu Xuan University)",
    "Đại học Phương Đông (Phuong Dong University)",
    "Đại học Quang Trung (Quang Trung University)",
    "Đại học Quốc Tế Sài Gòn - SIU (Saigon International University)",
    "Đại học công nghệ Sài Gòn - STU (Saigon Technology University)",
    "Đại học Võ Trường Toản - VTTU (Vo Truong Toan University)",
    "Đại học Tân Tạo - TTU (Tan Tao University)",
    "Đại học Thăng Long (Thang Long University)",
    "Đại học Kinh Tế - Tài Chính TPHCM - UEF (Ho Chi Minh City University of Economics and Finance (UEF))",
    "Đại học Quốc Tế PACIFIC Vietnam (Pacific Vietnam University)",
    "Đại học Văn Hiến (Van Hien University)",
    "Đại học Văn Lang (Van Lang University)",
    "Đại học Công nghệ Vạn Xuân - VXUT (Van Xuan University of Technology)",
    "Trường Đại học VinUni (VinUniversity)",
    "Đại học Thành Tây, Hà Nội (Western University Hanoi)",
    "Trường Đại học Lạc Hồng (Lac Hong University)",
    "Trường Đại học Kinh tế Công nghiệp Long An - DLA or LAU (Long An University of Economy and Industry)",
    "PACE Institute of Leadership and Management",
    "Trường Đại học Thái Bình (Thai Binh University)"
]